/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: (typeof import("element-plus/es"))["ElCheckbox"]
    ElCheckboxGroup: (typeof import("element-plus/es"))["ElCheckboxGroup"]
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: (typeof import("element-plus/es"))["ElDatePicker"]
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: (typeof import("element-plus/es"))["ElLink"]
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: (typeof import("element-plus/es"))["ElOption"]
    ElRadio: (typeof import("element-plus/es"))["ElRadio"]
    ElRadioGroup: (typeof import("element-plus/es"))["ElRadioGroup"]
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: (typeof import("element-plus/es"))["ElSelect"]
    ElSelectV2: (typeof import("element-plus/es"))["ElSelectV2"]
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: (typeof import("element-plus/es"))["ElSwitch"]
    ElTable: (typeof import("element-plus/es"))["ElTable"]
    ElTableColumn: (typeof import("element-plus/es"))["ElTableColumn"]
    ElTimePicker: (typeof import("element-plus/es"))["ElTimePicker"]
    FirstTable: typeof import('./src/components/FirstTable.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RemImg: (typeof import("./src/components/RemImg.vue"))["default"]
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: (typeof import("./src/components/Table.vue"))["default"]
  }
}
